config/routes.rb
Rails.application.routes.draw do
	root 'pictures#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users, only: [:show] do
  	get 'pictures' => 'pictures#user_pictures', as: 'pictures'
  	get 'pictures/new'=> 'pictures#new'
  end

 	get 'pictures/top' => 'pictures#top'

 	resources :pictures, except: [:index, :new] do
 		post 'comments/create' => 'comments#create'
 		patch 'ratings/update' => 'ratings#update'
 	end


 	resources :tags, only: [:show], param: :slug

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :picture

	validates :content, presence: true
end

app/models/picture.rb
class Picture < ApplicationRecord
	belongs_to :user
	has_many :comments
	has_one :rating
	has_many :picture_tags
	has_many :tags, through: :picture_tags

	has_attached_file :path, styles: { medium: "500x500>", small: "300x300>", thumb: "100x100>" }, 
										default_url: "/images/:style/missing.png",
										path: ":rails_root/app/assets/images/:username/:style/:basename.:extension",
										url: ":username/:style/:basename.:extension"

	Paperclip.interpolates('username') do |attachment, style|
		attachment.instance.user.name
	end

	validates :title, presence: true
	validates :path, presence: { message: "to picture can't be blank" }
  validates_attachment_content_type :path, content_type: /\Aimage\/.*\z/

  def tags_attributes=(tag_names)
		names = tag_names['0']['name'].split(', ')

    names.each do |name|
    	stripped_name = strip_tag_name(name)
      tag = Tag.find_or_create_by(name: stripped_name)

      self.tags << tag
    end
  end

  def add_rating
  	rating = self.build_rating
  	user = User.find(self.user_id)
  	rating.users << user
  	rating.save
  end

  def self.top_rated
    self.joins(:rating).order('ratings.value')
  end

  private

  def strip_tag_name(tag_name)
  	tag_name.gsub(/[.!?();:%$@*&{}|^\[\]`#~\/\\]/, '')
  end

end

app/models/picture_tag.rb
class PictureTag < ApplicationRecord
	belongs_to :picture
	belongs_to :tag
end

app/models/rating.rb
class Rating < ApplicationRecord
	has_many :user_ratings
	has_many :users, through: :user_ratings
	belongs_to :picture

	def average
		average = (self.value / self.total_votes)
		average.to_f / 10
	end
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :picture_tags
	has_many :pictures, through: :picture_tags

	before_validation :slugify

	validates :name, :slug, presence: true

	def to_param
		slug
	end

	def slugify
		self.slug = name.gsub(' ', '_').downcase
	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :pictures
  has_many :comments
  has_many :user_ratings
  has_many :ratings, through: :user_ratings

  validates :name, presence: true, uniqueness: true
  validates_format_of :name, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
  validate :validate_username

	def validate_username
	  if User.where(email: self.name).exists?
	    errors.add(:name, :invalid)
	  end
	end

  attr_accessor :login

  def login=(login)
    @login = login
  end

  def login
    @login || self.name || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["lower(name) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:name) || conditions.has_key?(:email)
      where(conditions.to_hash).first
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name.gsub(' ', '_')
    end
  end

  def has_not_voted?(rating)
    !self.ratings.include?(rating)
  end
end

app/models/user_rating.rb
class UserRating < ApplicationRecord
	belongs_to :user
	belongs_to :rating
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include Pundit
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  protected

  def configure_permitted_parameters
    added_attrs = [:name, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@comment = Comment.new(comment_params)
		@picture = Picture.find(params[:picture_id])

		@comment.user_id = current_user.id
		@comment.picture_id = @picture.id

		if @comment.save
			redirect_to picture_path(@picture)
		else
			flash[:notice] = "Something went wrong, please try again"
			redirect_to request.referer
		end

		authorize @comment
	end

	private

	def comment_params
		params.require(:comment).permit(:content)
	end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	after_action :verify_authorized, except: [:index, :show, :user_pictures, :top]

	def index
		@pictures = Picture.all
	end

	def new
		@picture = Picture.new
		authorize @picture
	end

	def create
		@picture = Picture.new(picture_params)
		@picture.user_id = current_user.id
		@picture.add_rating

		if @picture.save
			redirect_to picture_path(@picture)
		else
			render :new
		end

		authorize @picture
	end

	def show
		@picture = Picture.find(params[:id])
		@comment = Comment.new
		@rating = @picture.rating
	end

	def user_pictures
		@user = User.find(params[:user_id])
		@pictures = @user.pictures
	end

	def top
		@pictures = Picture.top_rated
	end

	private

	def picture_params
		params.require(:picture).permit(:title, :path, tags_attributes: [:name])
	end

	def user_not_authorized
	  flash[:alert] = "You need to be signed in to upload stuff."
	  redirect_to new_user_session_path
	end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
	def update
		@picture = Picture.find(params[:picture_id])
		@rating = @picture.rating

		@rating.value += params[:rating][:value].to_i * 10
		@rating.users << current_user
		@rating.total_votes += 1

		@rating.save

		redirect_to picture_url(@picture)
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def show
		@tag = Tag.find_by(slug: params[:slug])
	end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def readable_timestamp(model)
		model.created_at.strftime('%c')
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for @comment, url: picture_comments_create_path(@picture) do |f| %>
	<div>
		<%= f.text_area :content %>
	</div>
	
	<%= f.submit %>
<% end %>

app/views/comments/_show.html.erb
<% @picture.comments.reverse_each do |comment| %>
	<div>
		<p><%= comment.user.name %> says:<br>
		<%= comment.content %></p>
		<sup>on <%= readable_timestamp(comment) %></sup> 
	</div>
<% end %>

app/views/pictures/_comment_header.html.erb
<% if current_user %>
	Leave a comment
<% else %>
	<%= link_to 'Sign in to leave a comment', new_user_session_path %>
<% end %>

app/views/pictures/_list.html.erb
<% @pictures.each do |pic| %>
	<div>
		<h3><%= pic.title %></h3>
		<%= link_to (image_tag pic.path.url(:medium)), picture_path(pic) %>
		<p>
			Rating: <%= pic.rating.average %><br>
			Posted by: <%= link_to pic.user.name, user_path(pic.user) %>
		</p>
	</div>
<% end %>

app/views/pictures/index.html.erb
<h1>Welcome to Imgar, the image hosting site</h1>

<% if @pictures.count > 0 %>
	<p>Check out the <%= link_to("top rated", pictures_top_path) %></p>
<% end %>

<%= render 'list' %>

app/views/pictures/new.html.erb
<h1>Upload a new photo</h1>

<% if @picture.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@picture.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>
 
    <ul>
    <% @picture.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @picture, url: pictures_path, html: { multipart: true } do |f| %>
	<div class="field_with_errors">
		<%= f.label :title %>
		<%= f.text_field :title %>
	</div>

	<div class="field_with_errors">
		<%= f.file_field :path %>
	</div>

	<div>
		<h2>Add tags</h2>
		<%= f.fields_for :tags, Tag.new do |tag| %>
			<div>
				<%= tag.text_field :name %>
				<%= tag.label 'seperate each tag with a comma' %>
			</div>
		<% end %>
	</div>
	<div>
		<%= f.submit 'Upload' %>
	</div>
<%end%>

app/views/pictures/show.html.erb
<h1><%= @picture.title %></h1>

<%= link_to (image_tag @picture.path.url(:medium)), asset_path(@picture.path.url) %>

<div>
	<h2>Tags</h2>
	<% @picture.tags.each do |tag| %>
		<%= link_to tag.name, tag_path(tag) %>			
	<% end %>
</div>

<div>
	<%= render 'ratings/show' %>
</div>

<div>
	<div>
		<h3><%= render 'comment_header' %></h3>
		<%= render 'comments/form' if current_user %>
	</div>

	<div>
		<h3>Comments</h3>
		<%= render 'comments/show' %>
	</div>
</div>

app/views/pictures/top.html.erb
<h1>Top Rated</h1>

<%= render 'list' %>

app/views/pictures/user_pictures.html.erb
<h1><%= @user.name %>'s Pictures</h1>

<%= render 'list' %>

app/views/ratings/_show.html.erb
<h3>Current rating: <%= @rating.average %></h3>

<% if current_user && current_user.has_not_voted?(@rating) %>
	<%= form_for @rating, url: picture_ratings_update_path(@picture) do |f| %>
		<%= f.select :value, (1 .. 10) %>

		<%= f.submit "Rate this image" %>
	<% end %>
<% end %>

app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>

<% @tag.pictures.each do |pic| %>
	<div>
		<h3><%= pic.title %></h3>
		<%= link_to (image_tag pic.path.url(:medium)), picture_path(pic) %>
		<p>Posted by: <%= link_to pic.user.name, user_path(pic.user) %>
	</div>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<%= link_to "See all pictures posted by #{@user.name}", user_pictures_path(@user) %>

<h2>Comments</h2>

<% @user.comments.each do |comment| %>
	<p>Posted on: <%= link_to comment.picture.title, picture_path(comment.picture)  %><br>
	<%= comment.content %></p>
	<sup>on <%= readable_timestamp(comment) %></sup> 
<% end %>